sql_hostname: '192.168.0.141'
sql_username: 'dloar'
sql_password: 'rPiDBS3'
sql_main_database: 'stocks'
sql_port: 8585
ssh_host: '192.168.0.141'
ssh_psw: 'pXTVr8z0S2'
ssh_user: 'pi'
ssh_port: 22
sql_ip: '1.1.1.1.1'
email_user: 'deer9234@gmail.com'
email_psw: '3St89Kbb23X'
